"""
HTML Animation to MP4 Video Converter
Captures HTML5 canvas animations and combines with Edge-TTS voiceover
"""
import asyncio
import tempfile
import time
from pathlib import Path
from typing import Optional, Dict
import edge_tts
from moviepy.editor import VideoFileClip, AudioFileClip, concatenate_videoclips
from playwright.sync_api import sync_playwright
import config


class HTMLToVideoConverter:
    """Convert HTML5 canvas animations to MP4 with voiceover"""
    
    def __init__(self):
        self.temp_dir = Path(config.TEMP_DIR) / "html_animations"
        self.temp_dir.mkdir(parents=True, exist_ok=True)
        self.voice = "en-US-AndrewMultilingualNeural"
    
    async def generate_voiceover(self, script: str, output_path: Path) -> float:
        """Generate voiceover audio using Edge-TTS and return duration in seconds"""
        try:
            communicate = edge_tts.Communicate(script, self.voice)
            await communicate.save(str(output_path))
            
            # Get audio duration
            audio_clip = AudioFileClip(str(output_path))
            duration = audio_clip.duration
            audio_clip.close()
            
            return duration
        except Exception as e:
            print(f"⚠️ Edge-TTS failed ({str(e)}), using estimated duration")
            # Estimate duration: ~150 words per minute, ~5 chars per word
            words = len(script) / 5
            estimated_duration = (words / 150) * 60
            return max(estimated_duration, 10.0)  # Minimum 10 seconds
    
    def capture_html_animation(
        self,
        html_content: str,
        duration_seconds: float,
        output_path: Path,
        script: str = None
    ) -> Path:
        """Create a simple video from HTML content (Windows-compatible fallback)"""
        
        print("⚠️ Using simplified video generation (Playwright unavailable on Windows in this context)")
        
        # Create a simple colored video as placeholder
        # This is a fallback since Playwright has subprocess issues on Windows
        from moviepy.editor import ColorClip, TextClip, CompositeVideoClip
        
        # Create base video
        base_clip = ColorClip(
            size=(1920, 1080),
            color=(20, 30, 50),  # Dark blue background
            duration=duration_seconds
        )
        
        clips = [base_clip]
        
        # Add script text if provided (fallback when TTS fails)
        if script:
            try:
                # Split script into chunks that fit on screen
                words = script.split()
                lines = []
                current_line = []
                
                for word in words:
                    current_line.append(word)
                    if len(' '.join(current_line)) > 80:  # Max chars per line
                        lines.append(' '.join(current_line))
                        current_line = []
                
                if current_line:
                    lines.append(' '.join(current_line))
                
                # Create scrolling text effect
                full_text = '\n'.join(lines)
                
                text_clip = TextClip(
                    full_text,
                    fontsize=35,
                    color='white',
                    font='Arial',
                    size=(1700, None),
                    method='caption',
                    align='West'
                ).set_position(('center', 'center')).set_duration(duration_seconds)
                
                clips.append(text_clip)
                
                print("✅ Added script text overlay to video")
            except Exception as e:
                print(f"⚠️ Script text overlay failed: {e}")
        
        # Add title if no script
        if not script:
            try:
                title_text = TextClip(
                    "Educational Animation",
                    fontsize=70,
                    color='white',
                    font='Arial',
                    size=(1600, None)
                ).set_position('center').set_duration(duration_seconds)
                
                subtitle_text = TextClip(
                    "Generated by Sophi AI",
                    fontsize=40,
                    color='lightblue',
                    font='Arial'
                ).set_position(('center', 600)).set_duration(duration_seconds)
                
                clips.extend([title_text, subtitle_text])
            except Exception as e:
                print(f"⚠️ Text overlay failed: {e}")
        
        final_clip = CompositeVideoClip(clips) if len(clips) > 1 else base_clip
        
        # Write video
        final_clip.write_videofile(
            str(output_path),
            codec='libx264',
            audio=False,
            fps=24,
            preset='ultrafast'
        )
        
        final_clip.close()
        base_clip.close()
        
        return output_path
    
    def create_video_with_voiceover(
        self,
        html_content: str,
        script: str,
        output_filename: str
    ) -> Dict[str, str]:
        """
        Complete pipeline: Generate voiceover, capture HTML animation, combine them
        
        Args:
            html_content: Full HTML5 animation code
            script: Narration script for voiceover
            output_filename: Output MP4 filename
            
        Returns:
            Dict with video_path, audio_path, duration
        """
        print(f"🎙️ Generating voiceover with Edge-TTS...")
        
        # Generate voiceover (async call wrapped)
        audio_path = self.temp_dir / "voiceover.mp3"
        
        # Run async voiceover generation
        async def generate_audio():
            return await self.generate_voiceover(script, audio_path)
        
        try:
            loop = asyncio.new_event_loop()
            asyncio.set_event_loop(loop)
            duration = loop.run_until_complete(generate_audio())
            loop.close()
        except Exception as e:
            print(f"⚠️ Voiceover generation failed: {e}")
            duration = max((len(script) / 5 / 150) * 60, 10.0)
        
        # Check if audio file actually exists and has content
        has_audio = audio_path.exists() and audio_path.stat().st_size > 0
        
        if has_audio:
            print(f"✅ Voiceover generated ({duration:.1f}s)")
        else:
            print(f"⚠️ Voiceover unavailable, creating silent video ({duration:.1f}s)")
            # Remove empty/invalid audio file if it exists
            if audio_path.exists():
                audio_path.unlink()
        
        print(f"🎬 Capturing HTML animation...")
        
        # Capture HTML animation (now synchronous)
        # Pass script if audio is unavailable so text can be displayed
        video_no_audio = self.temp_dir / "animation_no_audio.mp4"
        script_for_video = script if not has_audio else None
        self.capture_html_animation(html_content, duration, video_no_audio, script_for_video)
        
        print(f"✅ HTML animation captured")
        
        # Combine video and audio (if available)
        output_path = Path(config.VIDEO_OUTPUT_DIR) / output_filename
        output_path.parent.mkdir(parents=True, exist_ok=True)
        
        video_clip = VideoFileClip(str(video_no_audio))
        
        if has_audio:
            print(f"🎵 Combining video and audio...")
            audio_clip = AudioFileClip(str(audio_path))
            final_clip = video_clip.set_audio(audio_clip)
            
            # Write final video
            final_clip.write_videofile(
                str(output_path),
                codec='libx264',
                audio_codec='aac',
                fps=24,
                preset='medium'
            )
            
            # Cleanup
            audio_clip.close()
            final_clip.close()
        else:
            print(f"🎵 Writing video without audio...")
            # Write video without audio
            video_clip.write_videofile(
                str(output_path),
                codec='libx264',
                fps=24,
                preset='medium'
            )
        
        # Cleanup
        video_clip.close()
        
        print(f"✅ Video with voiceover created: {output_path}")
        
        return {
            'video_path': str(output_path),
            'audio_path': str(audio_path),
            'duration': duration
        }
    
    def sync_create_video(
        self,
        html_content: str,
        script: str,
        output_filename: str
    ) -> Dict[str, str]:
        """Synchronous wrapper for create_video_with_voiceover"""
        import concurrent.futures
        
        # Run in thread pool to avoid asyncio loop conflicts with Playwright
        exception_box = []
        result_box = []
        
        def thread_target():
            try:
                result = self.create_video_with_voiceover(html_content, script, output_filename)
                result_box.append(result)
            except Exception as e:
                exception_box.append(e)
        
        with concurrent.futures.ThreadPoolExecutor() as executor:
            future = executor.submit(thread_target)
            future.result(timeout=180)  # 3 minutes timeout
        
        if exception_box:
            raise exception_box[0]
        
        if not result_box:
            raise Exception("Video generation failed without error")
            
        return result_box[0]
